# Generated by Django 5.2.4 on 2025-07-29 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=100, verbose_name='Carrera')),
                ('semestres', models.IntegerField(blank=True, null=True, verbose_name='Semestres')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre de la sección')),
                ('jornada', models.CharField(choices=[('diurna', 'Diurna'), ('vespertina', 'Vespertina')], verbose_name='jornada de la materia')),
            ],
        ),
        migrations.CreateModel(
            name='CarreraMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre', models.PositiveSmallIntegerField(verbose_name='Semestre')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carrera', verbose_name='Carrera')),
            ],
            options={
                'verbose_name': 'Carrera-Materia',
                'verbose_name_plural': 'Carreras-Materias',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Materia Name')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('carreras', models.ManyToManyField(related_name='materias', through='core.CarreraMateria', to='core.carrera', verbose_name='Carreras')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
            },
        ),
        migrations.AddField(
            model_name='carreramateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.materia', verbose_name='Materia'),
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_unidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=100, verbose_name='Unidad Name')),
                ('objetivo', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='core.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Unidad',
                'verbose_name_plural': 'Unidades',
            },
        ),
        migrations.AlterUniqueTogether(
            name='carreramateria',
            unique_together={('carrera', 'materia')},
        ),
        migrations.CreateModel(
            name='DocenteMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_asignadas', to='accounts.docente', verbose_name='Docente')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='docentes_asignados', to='core.materia', verbose_name='Materia')),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.seccion')),
            ],
            options={
                'verbose_name': 'Docente-Materia',
                'verbose_name_plural': 'Docentes-Materias',
                'unique_together': {('docente', 'materia', 'seccion', 'fecha_inicio')},
            },
        ),
    ]
