# Generated by Django 5.2.4 on 2025-07-31 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='fuente',
            field=models.CharField(blank=True, choices=[('deepseek', 'DeepSeek'), ('llama', 'Llama'), ('chatgpt', 'ChatGPT'), ('real', 'Real')], help_text='De dónde salió el ejercicio', max_length=100, null=True, verbose_name='fuente'),
        ),
    ]
