# Generated by Django 5.2.4 on 2025-07-31 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejercicios', '0002_alter_ejercicio_fuente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ejercicio',
            name='licencia',
            field=models.CharField(blank=True, choices=[('cc-by', 'CC BY'), ('cc-by-sa', 'CC BY-SA'), ('cc0', 'CC0'), ('mit', 'MIT'), ('gpl', 'GPL')], max_length=50, null=True, verbose_name='Licencia'),
        ),
    ]
