# Generated by Django 5.2.4 on 2025-07-30 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='semestre_actual',
            field=models.PositiveSmallIntegerField(blank=True, default=1, help_text='Semestre en el que está inscrito el estudiante', null=True, verbose_name='Semestre actual'),
        ),
        migrations.CreateModel(
            name='ProgresoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('fecha_finalizacion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_curso', 'En curso'), ('aprobada', 'Aprobada'), ('reprobada', 'Reprobada')], default='pendiente', max_length=10)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='accounts.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.materia')),
            ],
            options={
                'unique_together': {('estudiante', 'materia')},
            },
        ),
    ]
