# Generated by Django 5.2.4 on 2025-08-05 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20250805_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'Ya existe un usuario con este nombre de usuario.'}, help_text='Requerido. 50 caracteres o menos. Letras, números y @/./+/-/_ solamente.', max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Ingrese un nombre de usuario válido. Este valor solo puede contener letras, números y @/./+/-/_ caracteres.', 'invalid')], verbose_name='Nombre de usuario'),
        ),
    ]
